language: go
services:
  - docker
sudo: false
go:
  - 1.11.x
  - 1.12.x
  - tip
os:
  - linux
  - osx
matrix:
  include:
    - env: TEST_SUITE=lint
    - env: TEST_SUITE=examples
  allow_failures:
    - go: tip
  fast_finish: true
env:
  - GO111MODULE=on GOPROXY=https://proxy.golang.org TEST_SUITE=unit
script: 
- make test-suite
after_success:
  - bash <(curl -s https://codecov.io/bash)
